pub const AddressMode = enum {
    ZeroPageX,
    ZeroPageY,
    AbsoluteX,
    AbsoluteY,
    IndirectX,
    IndirectY,
    Implicit,
    Accumulator,
    Immediate,
    ZeroPage,
    Absolute,
    Relative,
    Indirect,
};

pub const Operation = enum {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
};

pub const Instruction = struct {
    operation: Operation,
    address_mode: AddressMode,
};

pub fn lookup(opcode: u8) ?Instruction {
    return switch (opcode) {
        0x69 => .{ .operation = .ADC, .address_mode = .Immediate },
        0x65 => .{ .operation = .ADC, .address_mode = .ZeroPage },
        0x75 => .{ .operation = .ADC, .address_mode = .ZeroPageX },
        0x6D => .{ .operation = .ADC, .address_mode = .Absolute },
        0x7D => .{ .operation = .ADC, .address_mode = .AbsoluteX },
        0x79 => .{ .operation = .ADC, .address_mode = .AbsoluteY },
        0x61 => .{ .operation = .ADC, .address_mode = .IndirectX },
        0x71 => .{ .operation = .ADC, .address_mode = .IndirectY },

        _ => null,
    };
}
